[package]
name = "hdfs_native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hdfs_native"

[dependencies]
bytes = "1"
prost = "0.11"
prost-types = "0.11"
roxmltree = "0.18.0"
url = "2.3.1"

[dependencies.uuid]
version = "1.3"
features = [
    "v4"
]

[build-dependencies]
prost-build = { version = "0.11" }
