[workspace]
members = [
    "crates/*",
    "python",
]
resolver = "2"

[workspace.dependencies]
bytes = "1"
chrono = "0.4"
futures = "0.3"
log = "0.4"
thiserror = "1"
tokio = "1"

[profile.bench]
debug = true
