name: build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Format
        run: cargo fmt -- --check

  # build:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         # - macos-11
  #         # - windows-latest
  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: true

  #     - name: Install minimal stable with clippy and rustfmt
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         profile: default
  #         toolchain: stable
  #         override: true

  #     - uses: Swatinem/rust-cache@v2

  #     - name: Install native libs
  #       run: sudo apt-get install -y libkrb5-dev libgsasl-dev protobuf-compiler

  #     # - name: build and lint with clippy
  #     #   run: cargo clippy --tests

  #     - name: Check docs
  #       run: cargo doc

  #     - name: Check
  #       run: cargo check

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-11
          # - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      # Disable full debug symbol generation to speed up CI build and keep memory down
      # "1" means line tables only, which is useful for panic tracebacks.
      RUSTFLAGS: -C debuginfo=1
      RUST_BACKTRACE: "1"
      RUST_LOG: debug

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: "stable"
          override: true

      - uses: Swatinem/rust-cache@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Install native libs
        run: sudo apt-get install -y libkrb5-dev libgsasl-dev protobuf-compiler krb5-user

      - name: Download Hadoop
        run: |
          wget -q https://dlcdn.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
          tar -xf hadoop-3.3.6.tar.gz
          echo "$GITHUB_WORKSPACE/hadoop-3.3.6/bin" >> $GITHUB_PATH

      - name: Run tests
        run: cargo test -- --test-threads=1
