name: python-release

on:
  push:
    branches:
      - master
    tags:
      - 'hdfs-v*'

jobs:
  validate-release-tag:
    name: Validate git tag
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/hdfs-v')
    steps:
      - uses: actions/checkout@v7
      - name: Compare tag with Rust and Python metadata
        run: |
          PUSHED_TAG=${GITHUB_REF##*/}
          PYTHON_VER=$(grep '^version' python/Cargo.toml | head -n 1 | awk '{print $3}' | tr -d '"')
          HDFS_VER=$(grep '^version' rust/hdfs-native/Cargo.toml | head -n 1 | awk '{print $3}' | tr -d '"')
          if [[ "${PYTHON_VER}" != "${HDFS_VER}" ]]; then
            echo "Python has version ${PYTHON_VER}, but hdfs-native has version ${HDFS_VER}."
            exit 1
          fi
          if [[ "${PUSHED_TAG}" != "hdfs-v${PYTHON_VER}" ]]; then
            echo "Package metadata has version ${PYTHON_VER}, but got tag ${PUSHED_TAG}."
            exit 1
          fi

  linux:
    runs-on: ${{ matrix.runner}}
    strategy:
      matrix:
        include:
          - target: x86_64
            runner: ubuntu-24.04
          - target: aarch64
            runner: ubuntu-24.04-arm
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v7
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter --manifest-path python/Cargo.toml
          sccache: 'true'
          container: quay.io/pypa/manylinux2014_${{ matrix.target }}
      - name: Build wheels free-threaded
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --interpreter python3.14t --manifest-path python/Cargo.toml
          sccache: 'true'
          container: quay.io/pypa/manylinux2014_${{ matrix.target }}
      - name: Upload wheels
        uses: actions/upload-artifact@v7
        with:
          name: wheels-linux-${{ matrix.target }}
          path: dist

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v7
      - name: Install free-threaded python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14t
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter --manifest-path python/Cargo.toml
          sccache: 'true'
      - name: Build wheels free-threaded
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --interpreter python3.14t --manifest-path python/Cargo.toml
          sccache: 'true'
      - name: Upload wheels
        uses: actions/upload-artifact@v7
        with:
          name: wheels-macos-${{ matrix.target }}
          path: dist

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install free-threaded python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14t
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist --find-interpreter --manifest-path python/Cargo.toml
          sccache: 'true'
      - name: Build wheels free-threaded
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist --interpreter python3.14t --manifest-path python/Cargo.toml
          sccache: 'true'
      - name: Upload wheels
        uses: actions/upload-artifact@v7
        with:
          name: wheels-windows
          path: dist

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist --manifest-path python/Cargo.toml
      - name: Upload sdist
        uses: actions/upload-artifact@v7
        with:
          name: wheels-sdist
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/hdfs-v')
    needs:
      - validate-release-tag
      - linux
      - macos
      - windows
      - sdist
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: wheels
          pattern: wheels-*
          merge-multiple: true
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Publish to PyPI
        run: uv publish --trusted-publishing always 'wheels/*'
